services:
  gateway:
    image: adminsudopixel/gateway:20221102_2
    container_name: sudopixel-gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_R2DBC_URL=r2dbc:postgresql://gateway-postgresql:5433/gateway
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://gateway-postgresql:5433/gateway
      - JHIPSTER_SLEEP=5
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - APPLICATION_SERVICES_GAME_SERVER_URI=http://host.docker.internal:7200
    ports:
      - "8080:8080"
    links:
      - "gateway-postgresql"
      - "jhipster-registry"
      
  gateway-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    command: -p 5433
      
  jhipster-registry:
    image: jhipster/jhipster-registry:v7.3.0
    volumes:
      - ./central-server-config:/central-config
    # By default the JHipster Registry runs with the "dev" and "native"
    # Spring profiles.
    # "native" profile means the filesystem is used to store data, see
    # http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/jhipster/jhipster-registry/
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=central-config
    ports:
      - 8761:8761
      
  sudopixel-game-server_db:
    image: postgres:12.5
    container_name: sudopixel-game-server-db
    ports:
      - "5439:5432"
    volumes:
      - ./volumes/game_server_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "P@ssword123"
      POSTGRES_DB: "sudopixel-game-server"
      PGDATA: "/var/lib/postgresql/data/pgdata"
  
  sudopixel-game-server:
    image: adminsudopixel/sudopixel-game-server
    container_name: sudopixel-game-server
    ports:
      - "7200:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      GATEWAY_URL: "http://host.docker.internal:8080"
      # todo: move to secrets  
      DB_CONNECTION_STRING: "Host=sudopixel-game-server-db;Database=sudopixel-game-server;Port=5432;Username=postgres;Password=P@ssword123;"
    links:
      - sudopixel-game-server_db
    restart: on-failure   
